-- creates a database
CREATE DATABASE database_name;

-- switches active database connection
Use database_name

-- deletes the database
DROP DATABASE database_name;

-- Delete the dvdstore database (IF EXISTS)
DROP DATABASE IF EXISTS dvdstore;

--basic syntax
CREATE TABLE table_name
(
  column_name1 data_type(size),
  column_name2 data_type(size) NOT NULL,
  column_name3 data_type(size),
  CONSTRAINT pk_column_1 PRIMARY KEY (column_name1),
  CONSTRAINT fk_column_2 FOREIGN KEY (column_name2) REFERENCES table_name(column_1)    
);

--Pulled from the dvdstore.sql
CREATE TABLE customer (
    customer_id integer identity NOT NULL,
    store_id integer NOT NULL,
    first_name varchar(45) NOT NULL,
    last_name varchar(45) NOT NULL,
    email varchar(50),
    address_id integer NOT NULL,
    activebool varchar(5) DEFAULT 'true' NOT NULL,
    active bit,
    CONSTRAINT pk_customer_customer_id PRIMARY KEY (customer_id),
    CONSTRAINT ck_customer_activebool CHECK (activebool = 'true' OR activebool='false')
);
GO

--Auto generated by MSSMS
CREATE TABLE [dbo].[customer](
	[customer_id] [int] IDENTITY(1,1) NOT NULL,
	[store_id] [int] NOT NULL,
	[first_name] [varchar](45) NOT NULL,
	[last_name] [varchar](45) NOT NULL,
	[email] [varchar](50) NULL,
	[address_id] [int] NOT NULL,
	[activebool] [varchar](5) NOT NULL,
	[active] [bit] NULL,
 CONSTRAINT [pk_customer_customer_id] PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);
GO

-- Modifies a part of a table
ALTER TABLE [dbo].[customer] ADD  DEFAULT ('true') FOR [activebool]
GO

-- deletes a table from the database
DROP TABLE table_name



-- Switch to the system (aka master) database
USE master;
GO

-- Delete the dvdstore database (IF EXISTS)
DROP DATABASE IF EXISTS dvdstore;
GO

-- Create a new dvdstore database
CREATE DATABASE dvdstore;
GO

-- Switch to the dvdstore database
USE dvdstore
GO